In [14]:
import numpy as np
import os
from statistic import *

In [2]:
def convert_function(W,H,x,n,x1,y1,w1,h1):
    """
    Given Width(W), Height(H) of the picture, length of the sqaure x
    and the crater position (x1,y1,w1,h1) in small tiles, return position
    and size of crater relative to the input image.

    Parameters
    ----------
    W : Width of input image
    H : Height of input image
    x : length of small tiles
    n : number of picture
    x1, y1, w1, h1 : crater position

    Returns
    -------
    result : np.array 
        Position and size of crater relative to the input image.


    Examples
    --------
    >>> W = 27291
    >>> H = 54582
    >>> x = 2048
    >>> n = 89
    >>> x1 = 0.053192
    >>> y1 = 0.628065
    >>> w1 = 0.519336
    >>> h1 = 0.486487
    >>> result = convert(W,H,x,n,x1,y1,w1,h1)
    >>> result
    array([20588.937216,  7430.27712 ,  1063.600128,   996.325376])
    
    """
    r = W // x 
    c = H // x
    print(r,c)
    row = (n-1) // c
    col = n - row*c -1
    print(row,col)
    x2 = (col*x+x*x1)
    y2 = (row*x+x*y1)
    w2 = w1*x
    h2 = h1*x
    
    return np.array([x2,y2,w2,h2])

In [4]:
rootdir = 'userinput1'
# iterate over files in
# that directory
for root, dirs, files in os.walk(rootdir):
    files.sort()
    for filename in files:
        if filename.__contains__('.DS_Store') == False:
            with open(os.path.join(root, filename)) as f:
                for line in f:
                    data = np.array(line.strip().split(','),dtype=float)
                    print(data)
            # print(os.path.join(root, filename))

[0.06490385 0.33293269 0.03365385 0.03125   ]
[0.41346154 0.72716346 0.10096154 0.09855769]
[0.89182692 0.93269231 0.08173077 0.08173077]
[0.04086538 0.69230769 0.03365385 0.03365385]
[0.52884615 0.27403846 0.05288462 0.05288462]
[0.61778846 0.421875   0.09134615 0.08894231]
[0.86538461 0.15144231 0.04326923 0.04326923]
[0.78605769 0.12740385 0.03846154 0.03846154]
[0.52884615 0.27403846 0.05288462 0.05288462]
[0.86538461 0.15144231 0.04326923 0.04326923]
[0.78605769 0.12740385 0.03846154 0.03846154]
[0.52884615 0.27403846 0.05288462 0.05288462]


In [5]:
W = 27291
H = 54582
x = 2048
n = 89
x1 = 0.053192
y1 = 0.628065
w1 = 0.519336
h1 = 0.486487

In [6]:
W_ = 27291
H_ = 54582
x_ = 256
n_ = 9163
x1_ = 0.527457
y1_ = 0.033216
w1_ = 0.395133
h1_ = 0.390618

In [7]:
convert_function(W,H,x,n,x1,y1,w1,h1)


13 26
3 10


array([20588.937216,  7430.27712 ,  1063.600128,   996.325376])

In [8]:
convert_function(W_,H_,x_,n_,x1_,y1_,w1_,h1_)

106 213
43 3


array([  903.028992, 11016.503296,   101.154048,    99.998208])

In [9]:
# def convert input path (pic1 pic2)
# output path .csv

In [10]:
def remove_ds_store(file_list):
    """
        Removes strings that contain the substring '.DS_Store'.

        This function is used in the import_folder() method (see user_int.py).
        It is also used in the check_file_names(folder_1, folder_2) function below.

        Parameters
        ----------
        file_list : list of strings.

        Returns
        -------
        list: file_list but without the strings which contain the substring '.DS_Store'.

        """
    return [item for item in file_list if '.DS_Store' not in item]

In [11]:
rootdir = 'userinput1'

filelist = []
for root, dirs, files in os.walk(rootdir):
    files.sort()

    for filename in files:
        filelist.append(filename)
print(filelist)
filelist = remove_ds_store(filelist)
print("\n", filelist)

['.DS_Store', '.DS_Store', '.DS_Store', 'aeolis_42_0.csv', 'aeolis_42_5.csv', '.DS_Store', 'aeolis_35_0.csv', 'aeolis_40_1.csv', '.DS_Store', 'aeolis_30_6.csv', 'aeolis_30_6.csv']

 ['aeolis_42_0.csv', 'aeolis_42_5.csv', 'aeolis_35_0.csv', 'aeolis_40_1.csv', 'aeolis_30_6.csv', 'aeolis_30_6.csv']


In [12]:
def check_image_folder(image_folder):
    """
        Checks that the 'images' subdirectory exists.
        Checks that the images in the subdirectory are of an appropriate format (accepts only .jpg, .png, .tif).
        If no errors are found, appends the name and path of the images to a dictionary, and returns the dictionary.
        This function is used in the import_folder() method (see user_int.py).
        Parameters
        ----------
        image_folder: path to the 'images' folder.
        Returns
        -------
        - A string: if the string "images" is returned, no errors were found; otherwise, the string describes the error.
        - files: dictionary which contains the name and path of the images in the image_folder.
        (Note: the dictionary is empty if an error is found.)
        """

    files = {'name':[], 'path':[]}

    if not (os.path.exists(image_folder)):
        return "The input folder should contain a subdirectory called images.", files

    for file in os.listdir(image_folder):
        if not (file.endswith(".png") or file.endswith(".jpg") or file.endswith(".tif") or file.endswith(".DS_Store")):
            return f"The image: '{file}' is of the wrong format.\nPlease change the format of the image or delete the file.", files
        else:
            files['name'].append(file)
            files['path'].append(image_folder + '/' +  file)

    return "images", files

In [13]:
check_image_folder('Archive/data')

("The image: 'images' is of the wrong format.\nPlease change the format of the image or delete the file.",
 {'name': ['.DS_Store'], 'path': ['Archive/data/.DS_Store']})

In [18]:
a1,b1,c1,d1 = 0.8557692307692307,0.48677884615384615,0.1201923076923077,0.12259615384615384
a2,b2,c2,d2 = 0.9423076923076923,0.7584134615384616,0.08173076923076923,0.07932692307692307
iouCal(a1,b1,a2,b2,c1,d1,c2,d2)

0

In [20]:
a1,b1,c1,d1 = 0.7175480769230769,0.6225961538461539,0.06009615384615385,0.057692307692307696
a2,b2,c2,d2 = 0.7236538461538461,0.624,0.078461538461538464,0.038461538461538464
iouCal(a1,b1,a2,b2,c1,d1,c2,d2)

0.8337628845764702